indydutch_image:
    resource: "@IndydutchImageBundle/Resources/config/routing.xml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

# app/config/routing.yml
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
